---
- hosts: myWebservers
  tasks:
    - name: i want to install java on uuntu
      apt:
        name: "{{myjavaonubuntu}}"
        state: present
      
      when: ansible_os_family=="Debian" 
    
