---
- hosts: all
  become: yes
  tasks:
    - name: i want to install apache2 webserver on uuntu
      apt:
        name: apache2
        state: present
    - name: start apache2 service
      service: 
        name: apache2
        state: started

       
    
